# Generated by Django 3.0.3 on 2020-04-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200424_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('out of delivery', 'out of delivery'), ('delivered', 'delivered')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('in door', 'in door'), ('out door', 'out door')], max_length=200, null=True),
        ),
    ]
